package SumaApp;

/**
* SumaApp/sumaHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SumaApp.idl
* lunes 9 de abril de 2018 19H44' COT
*/

public final class sumaHolder implements org.omg.CORBA.portable.Streamable
{
  public SumaApp.suma value = null;

  public sumaHolder ()
  {
  }

  public sumaHolder (SumaApp.suma initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = SumaApp.sumaHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    SumaApp.sumaHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return SumaApp.sumaHelper.type ();
  }

}
