package SumaApp;


/**
* SumaApp/sumaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SumaApp.idl
* lunes 9 de abril de 2018 19H44' COT
*/

public interface sumaOperations 
{
  int sumar (int primernumero, int segundonumero);
  void shutdown ();
} // interface sumaOperations
