package SumaApp;


/**
* SumaApp/suma.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SumaApp.idl
* lunes 9 de abril de 2018 19H44' COT
*/

public interface suma extends sumaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface suma
